### ISSUE TITLE
[HELP] How to get windowNumber for a window?

### ISSUE THREAD

**Issue by Nithin-anim** [karaggeorge/mac-focus-window#2]
Hi, I am working on electron environment where I want to focus a particular window and bring it on top of all windows.My question is how to get access to windowNumber property for a particular window.I already looked into the mac-windows package but it doesn't return the windowNumber of the mac windows when invoked.

So is there any way to get a windowNumber in a node environment or can u add functionality in the package such that I can focus the window by just passing the name of the window.

**Comment by karaggeorge** [comment]
Hey, I updated the https://github.com/karaggeorge/mac-windows package to now return the window number

Keep in mind this change:

Requires macOS 10.12 or later. macOS 10.13 or earlier needs to download the [Swift runtime support libraries](https://support.apple.com/kb/DL1998).

**Comment by Nithin-anim** [comment]
Thanks for updating the package.Was able to achieve the desired functionality with the 2 packages.
